### ISSUE TITLE
Support PeerTube videos

### ISSUE THREAD

**Issue by Genfood** [CreatureSurvive/Arctic-Issues#1]
Supporting video playback of PeerTube videos would be a great addition.

Example post: https://feddit.de/post/4341500

**Comment by CreatureSurvive** [comment]
PeerTube videos are currently supported for in-line playback in the Posts feed, playback in individual posts and comments should be included in the next release. 

PeerTube playback is disabled by default, but it can be enabled in _Settings > Media Settings > Load Piped Videos_, there are also settings to convert YouTube links to Piped, and choose which Piped instance to use for playback.

I'll leave this issue open until I have piped videos working in Posts and Comments.

_Note:_ in feeds that have many Piped links, some of them may fail to load. This is because CloudFlair blocks the API requests when to many are sent in quick succession. I'm looking into a fix for this, but currently the best solution I had was to use load balancing and distribute requests to multiple Piped instances.

**Comment by Genfood** [comment]
Isn't piped something else than PeerTube? For my understanding piped is a YouTube frontend and PeerTube is what Lemmy is for Reddit but for YouTube. 

For this post: https://feddit.de/post/4341500

I just got a link preview:
![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/a4e97158-6055-400b-83fe-dd7bff39b0d3)

Piped is activated in the media settings.

But maybe I just don't understand what in-line playback means. 😅

**Comment by CreatureSurvive** [comment]
Yes you are correct. I just mixed the two up. I will definitely look into supporting PeerTube.

**Comment by CreatureSurvive** [comment]
I finally got around to implementing the PeerTube API in Arctic, I haven't activated it just yet though. Since PeerTube doesn't have a common url, I'll need to add support for adding custom domains for utilizing the PeerTube API. I should hopefully have this added in the next release.

**Comment by Genfood** [comment]
Isn't it possible to detect if a domain is hosting peer tune instance or not by a request?

**Comment by CreatureSurvive** [comment]
I finally go around to fixing this, and PeerTube videos are supported as of v0.4.2.3.
