### ISSUE TITLE
Can't see comments under my posts anymore

### ISSUE THREAD

**Issue by Genfood** [CreatureSurvive/Arctic-Issues#8]
In the newest release I can't see comments below my posts.

![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/22c62a46-d3fd-4749-a97e-06c2febbe8dc)

The same post using the web app shows the comments, I also got notifications telling me about a new comment.

![image](https://github.com/CreatureSurvive/Arctic-Issues/assets/11618226/7fe91778-7d9f-4c8f-8993-df0c63d8ca03)

**Comment by Genfood** [comment]
I noticed that this is only the case for posts made by me in a different instance. Post on my home instance are working perfectly fine.

**Comment by CreatureSurvive** [comment]
@Genfood 

Sorry for the late response. My notifications for issues stoped working.

This looks like an issue with the comment listing type being set to _local_ rather than _all_. I added the footer message _"viewing local comments only"_ to try and make this more apparent, but what I need to do is move the listing button so users know what it is set to.

In the mean time, to resolve this issue, you can tap the top right button in the navigation bar and select _All_ to show all comments rather than just the ones on the local instance.

**Comment by Genfood** [comment]
Oh, I didn't know that's a thing. I don't know why one would only want to read local comments? 😅 do you think that's a good thing?

**Comment by CreatureSurvive** [comment]
@Genfood this option honestly seems to be more trouble than it's worth. I implemented it because it's included in the API and I wanted to support as many options as possible. It seems to cause more confusion than anything. I see that even the webUI doesn't seem to offer it as an option. I may end up just removing it all together. Like you said, I don't see the usefulness except for maybe admins moderating local comments.

**Comment by Genfood** [comment]
Yeah, intuitively I would always expect to see all comments available for a post. I don't see it making sense. 😅
